package cn.plou.web.charge.chargeconfig.entity;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sms_info
 *短信记录
 */
@Data
public class SmsInfo  implements Serializable {


    private static final long serialVersionUID = 1L;



    /** 短信ｉｄ*/
    private String primaryId;

    /** 年度ｉｄ*/
    private String annual;

    /** 公司ｉｄ*/
    private String companyId;

    /** 用户ｉｄ*/
    private String consumerId;


    /** 短信主题*/
    private String title;

    /** 短信内容*/
    private String contents;

    /** 接收人*/
    private String receiver;

    /** 手机号*/
    private String receiverPhone;

    /** 发送状态：成功，失败*/
    private String status;

    /** 保留１*/
    private String memo1;

    /** 保留２*/
    private String memo2;

    /** 创建时间*/
    private Date createDate;

    /** 创建者*/
    private String createUser;

    /** 更新时间*/
    private Date updateDate;

    /** 更新者*/
    private String updateUser;


}