package cn.plou.web.charge.chargeconfig.entity;

import lombok.Data;
import lombok.Getter;
import lombok.Setter;

import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table price_accuracy_info
 *
 * @mbg.generated do_not_delete_during_merge
 */

@Getter
@Setter
public class PriceAccuracyInfo {
    /** 收费精度ＩＤ*/
    private String primaryId;

    /** 公司ＩＤ*/
    @NotNull(message = "公司ＩＤ不能为空")
    private String companyId;


    /** 现金收费精度*/
    @NotEmpty(message = "现金收费精度不能为空")
    private String cashAccuracy;

    /** 非现金收费精度*/
    @NotNull(message = "非现金收费精度不能为空")
    private String notCashAccuracy;


    /** 备注*/
    private String notes;

    private Date   createDate;

    private String createUser;


    private Date   updateDate;

    private String updateUser;



}